/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyWeightEntry { 'weight' : number, 'date' : string }
export interface DailyTotals {
  'fat' : number,
  'carbs' : number,
  'calories' : number,
  'protein' : number,
}
export interface Exercise {
  'weight' : number,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
}
export interface FoodEntry {
  'fat' : number,
  'carbs' : number,
  'date' : string,
  'calories' : number,
  'name' : string,
  'protein' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutSession {
  'duration' : number,
  'date' : string,
  'name' : string,
  'exercises' : Array<Exercise>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBodyWeightEntry' : ActorMethod<[BodyWeightEntry], undefined>,
  'addFoodEntry' : ActorMethod<[FoodEntry], undefined>,
  'addWorkoutSession' : ActorMethod<[WorkoutSession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBodyWeightEntry' : ActorMethod<[string], undefined>,
  'deleteFoodEntry' : ActorMethod<[string, string], undefined>,
  'deleteWorkoutSession' : ActorMethod<[string, string], undefined>,
  'getAllBodyWeightEntries' : ActorMethod<[], Array<BodyWeightEntry>>,
  'getAllWorkoutSessions' : ActorMethod<[], Array<WorkoutSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyTotals' : ActorMethod<[string], DailyTotals>,
  'getFoodEntriesByDate' : ActorMethod<[string], Array<FoodEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutSessionsByDate' : ActorMethod<[string], Array<WorkoutSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];