/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BodyWeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'date' : IDL.Text,
});
export const FoodEntry = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'date' : IDL.Text,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'protein' : IDL.Float64,
});
export const Exercise = IDL.Record({
  'weight' : IDL.Float64,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
});
export const WorkoutSession = IDL.Record({
  'duration' : IDL.Float64,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const DailyTotals = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'protein' : IDL.Float64,
});
export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'totalVolumeLast7Days' : IDL.Float64,
  'totalVolumeAllTime' : IDL.Float64,
  'principalText' : IDL.Text,
  'workoutCountLast7Days' : IDL.Nat,
  'workoutCountAllTime' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBodyWeightEntry' : IDL.Func([BodyWeightEntry], [], []),
  'addFoodEntry' : IDL.Func([FoodEntry], [], []),
  'addWorkoutSession' : IDL.Func([WorkoutSession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteBodyWeightEntry' : IDL.Func([IDL.Text], [], []),
  'deleteFoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteWorkoutSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllBodyWeightEntries' : IDL.Func(
      [],
      [IDL.Vec(BodyWeightEntry)],
      ['query'],
    ),
  'getAllWorkoutSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTotals' : IDL.Func([IDL.Text], [DailyTotals], ['query']),
  'getFoodEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutSessionsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BodyWeightEntry = IDL.Record({
    'weight' : IDL.Float64,
    'date' : IDL.Text,
  });
  const FoodEntry = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'date' : IDL.Text,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const Exercise = IDL.Record({
    'weight' : IDL.Float64,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
  });
  const WorkoutSession = IDL.Record({
    'duration' : IDL.Float64,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const DailyTotals = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'protein' : IDL.Float64,
  });
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'totalVolumeLast7Days' : IDL.Float64,
    'totalVolumeAllTime' : IDL.Float64,
    'principalText' : IDL.Text,
    'workoutCountLast7Days' : IDL.Nat,
    'workoutCountAllTime' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBodyWeightEntry' : IDL.Func([BodyWeightEntry], [], []),
    'addFoodEntry' : IDL.Func([FoodEntry], [], []),
    'addWorkoutSession' : IDL.Func([WorkoutSession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteBodyWeightEntry' : IDL.Func([IDL.Text], [], []),
    'deleteFoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteWorkoutSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllBodyWeightEntries' : IDL.Func(
        [],
        [IDL.Vec(BodyWeightEntry)],
        ['query'],
      ),
    'getAllWorkoutSessions' : IDL.Func(
        [],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTotals' : IDL.Func([IDL.Text], [DailyTotals], ['query']),
    'getFoodEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutSessionsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };